name: Build
on: [push]
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Check
        run: |
          ./gradlew --no-daemon --console=plain check
      - name: Build
        run: |
          ./gradlew --no-daemon --console=plain server:jibDockerBuild --image=scalardev/trawler:$GITHUB_SHA
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push
        if: github.ref == 'refs/heads/master'
        run: |
          ./gradlew --no-daemon --console=plain server:jib --image=scalardev/trawler:$GITHUB_SHA

  ui:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd ui
          docker build -t scalardev/trawler-ui:$GITHUB_SHA .
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push
        if: github.ref == 'refs/heads/master'
        run: |
          docker push scalardev/trawler-ui:$GITHUB_SHA 

  agent:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd python
          docker build -t scalardev/trawler-agent:$GITHUB_SHA .
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push
        if: github.ref == 'refs/heads/master'
        run: |
          docker push scalardev/trawler-agent:$GITHUB_SHA 
